<?php

declare(strict_types=1);

/*
 * APIMATICCALCULATORLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIMATICCALCULATORLib\Tests;

use APIMATICCALCULATORLib\APIMATICCALCULATORClient;
use APIMATICCALCULATORLib\APIMATICCALCULATORClientBuilder;
use Core\Types\CallbackCatcher;

class ClientFactory
{
    public static function create(CallbackCatcher $httpCallback): APIMATICCALCULATORClient
    {
        $clientBuilder = APIMATICCALCULATORClientBuilder::init();
        $clientBuilder = self::addConfigurationFromEnvironment($clientBuilder);
        $clientBuilder = self::addTestConfiguration($clientBuilder);
        return $clientBuilder->httpCallback($httpCallback)->build();
    }

    public static function addTestConfiguration(
        APIMATICCALCULATORClientBuilder $builder
    ): APIMATICCALCULATORClientBuilder {
        return $builder;
    }

    public static function addConfigurationFromEnvironment(
        APIMATICCALCULATORClientBuilder $builder
    ): APIMATICCALCULATORClientBuilder {
        $timeout = getenv('APIMATICCALCULATOR_LIB_TIMEOUT');
        $numberOfRetries = getenv('APIMATICCALCULATOR_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('APIMATICCALCULATOR_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('APIMATICCALCULATOR_LIB_ENVIRONMENT');

        if (!empty($timeout) && \is_numeric($timeout)) {
            $builder->timeout(intval($timeout));
        }

        if (!empty($numberOfRetries) && \is_numeric($numberOfRetries)) {
            $builder->numberOfRetries(intval($numberOfRetries));
        }

        if (!empty($maximumRetryWaitTime) && \is_numeric($maximumRetryWaitTime)) {
            $builder->maximumRetryWaitTime(intval($maximumRetryWaitTime));
        }

        if (!empty($environment)) {
            $builder->environment($environment);
        }

        return $builder;
    }
}
