<?php

declare(strict_types=1);

/*
 * APIMATICCALCULATORLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIMATICCALCULATORLib;

/**
 * Baseurl aliases
 */
class Server
{
    public const CALCULATOR = 'Calculator';
}
